<a href="https://colab.research.google.com/github/wcaine93/Advanced-Python-Project/blob/main/src/data-inspection-and-cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A: Import and process the csv data

In [21]:
import pandas as pd

### 1. Load the csv data.

In [22]:
df = pd.read_csv('concrete_data2.csv')

### 2. Get a quick overview by printing the first 10 rows of the DataFrame, viewing the last 5 rows of the DataFrame, and showing all the rows.

In [24]:
df.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,NaN,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29

In [33]:
df.tail()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1028,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1029,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1030,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1031,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [46]:
print(df.to_string())

      Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  Coarse Aggregate  Fine Aggregate  Age  Strength
0      540.0                 0.0      0.0  162.0               2.5            1040.0           676.0   28     79.99
1      540.0                 0.0      0.0  162.0               2.5            1055.0           676.0   28     61.89
2      332.5               142.5      0.0  228.0               0.0             932.0           594.0  270     40.27
3      332.5               142.5      0.0  228.0               0.0             932.0           594.0  365     41.05
4      198.6               132.4      0.0    NaN               0.0             978.4           825.5  360     44.30
5      266.0               114.0      0.0  228.0               0.0             932.0           670.0   90     47.03
6      380.0                95.0      0.0  228.0               0.0             932.0           594.0  365     43.70
7      380.0                95.0      0.0  228.0               0.0             932.0           594.0   28     36.45
8      266.0               114.0      0.0  228.0               0.0             932.0           670.0   28     45.85
9      475.0                 0.0      0.0  228.0               0.0             932.0           594.0   28     39.29
10     198.6               132.4      0.0  192.0               0.0             978.4           825.5   90     38.07
11     198.6               132.4      0.0  192.0               0.0             978.4           825.5   28     28.02
12     427.5                47.5      0.0  228.0               0.0             932.0           594.0  270     43.01
13     190.0               190.0      0.0  228.0               0.0             932.0           670.0   90     42.33
14     304.0                76.0      0.0  228.0               0.0             932.0           670.0   28     47.81
15     380.0                 0.0      0.0  228.0               0.0             932.0           670.0   90     52.91
16     139.6               209.4      0.0  192.0               0.0            1047.0           806.9   90     39.36
17     342.0                38.0      0.0  228.0               0.0             932.0           670.0  365     56.14
18     380.0                95.0      0.0  228.0               0.0             932.0           594.0   90     40.56
19     475.0                 0.0      0.0  228.0               0.0             932.0           594.0  180     42.62
20     427.5                47.5      0.0  228.0               0.0             932.0           594.0  180     41.84
21     139.6               209.4      0.0  192.0               0.0            1047.0           806.9   28     28.24
22     139.6               209.4      0.0  192.0               0.0            1047.0           806.9    3      8.06
23     139.6               209.4      0.0  192.0               0.0            1047.0           806.9  180     44.21
24     380.0                 0.0      0.0  228.0               0.0             932.0           670.0  365     52.52
25     380.0                 0.0      0.0  228.0               0.0             932.0           670.0  270     53.30
26     380.0                95.0      0.0  228.0               0.0             932.0           594.0  270     41.15
27     342.0                38.0      0.0  228.0               0.0             932.0           670.0  180     52.12
28     427.5                47.5      0.0  228.0               0.0             932.0           594.0   28     37.43
29     475.0                 0.0      0.0  228.0               0.0             932.0           594.0    7     38.60
30     304.0                76.0      0.0  228.0               0.0             932.0           670.0  365     55.26
31     266.0               114.0      0.0  228.0               0.0             932.0           670.0  365     52.91
32     198.6               132.4      0.0  192.0               0.0             978.4           825.5  180     41.72
33     475.0                 0.0      0.0  228.0               0.0             932.0           594.0  270     42.13
34     190.0               190.0      0.0  228.0               0.0             932.0           670.0  365     53.69
35     237.5               237.5      0.0  228.0               0.0             932.0           594.0  270     38.41
36     237.5               237.5      0.0  228.0               0.0             932.0           594.0   28     30.08
37     332.5               142.5      0.0  228.0               0.0             932.0           594.0   90     37.72
38     475.0                 0.0      0.0  228.0               0.0             932.0           594.0   90     42.23
39     237.5               237.5      0.0  228.0               0.0             932.0           594.0  180     36.25
40     342.0                38.0      0.0  228.0               0.0             932.0           670.0   90     50.46
41     427.5                47.5      0.0  228.0               0.0             932.0           594.0  365     43.70
42     237.5               237.5      0.0  228.0               0.0             932.0           594.0  365     39.00
43     380.0                 0.0      0.0  228.0               0.0             932.0           670.0  180     53.10
44     427.5                47.5      0.0  228.0               0.0             932.0           594.0   90     41.54
45     427.5                47.5      0.0  228.0               0.0             932.0           594.0    7     35.08
46     349.0                 0.0      0.0  192.0               0.0            1047.0           806.9    3     15.05
47     380.0                95.0      0.0  228.0               0.0             932.0           594.0  180     40.76
48     237.5               237.5      0.0  228.0               0.0             932.0           594.0    7     26.26
49     380.0                95.0      0.0  228.0               0.0             932.0           594.0    7     32.82
50     332.5               142.5      0.0  228.0               0.0             932.0           594.0  180     39.78
51     190.0               190.0      0.0  228.0               0.0             932.0           670.0  180     46.93
52     237.5               237.5      0.0  228.0               0.0             932.0           594.0   90     33.12
53     304.0                76.0      0.0  228.0               0.0             932.0           670.0   90     49.19
54     139.6               209.4      0.0  192.0               0.0            1047.0           806.9    7     14.59
55     198.6               132.4      0.0  192.0               0.0             978.4           825.5    7     14.64
56     475.0                 0.0      0.0  228.0               0.0             932.0           594.0  365     41.93
57     198.6               132.4      0.0  192.0               0.0             978.4           825.5    3      9.13
58     304.0                76.0      0.0  228.0               0.0             932.0           670.0  180     50.95
59     332.5               142.5      0.0  228.0               0.0             932.0           594.0   28     33.02
60     304.0                76.0      0.0  228.0               0.0             932.0           670.0  270     54.38
61     266.0               114.0      0.0  228.0               0.0             932.0           670.0  270     51.73
62     310.0                 0.0      0.0  192.0               0.0             971.0           850.6    3      9.87
63     190.0               190.0      0.0  228.0               0.0             932.0           670.0  270     50.66
64     266.0               114.0      0.0  228.0               0.0             932.0           670.0  180     48.70
65     342.0                38.0      0.0  228.0               0.0             932.0           670.0  270     55.06
66     139.6               209.4      0.0  192.0               0.0            1047.0           806.9  360     44.70
67     332.5               142.5      0.0  228.0               0.0             932.0           594.0    7     30.28
68     190.0               190.0      0.0  228.0               0.0             932.0           670.0   28     40.86
69     485.0                 0.0      0.0  146.0               0.0            1120.0           800.0   28     71.99
70     374.0               189.2      0.0  170.1              10.1             926.1           756.7    3     34.40
71     313.3               262.2      0.0  175.5               8.6            1046.9           611.8    3     28.80
72     425.0               106.3      0.0  153.5              16.5             852.1           887.1    3     33.40
73     425.0               106.3      0.0  151.4              18.6             936.0           803.7    3     36.30
74     375.0                93.8      0.0  126.6              23.4             852.1           992.6    3     29.00
75     475.0               118.8      0.0  181.1               8.9             852.1           781.5    3     37.80
76     469.0               117.2      0.0  137.8              32.2             852.1           840.5    3     40.20
78     388.6                97.1      0.0  157.9              12.1             852.1           925.7    3     28.10
79     531.3                 0.0      0.0  141.8              28.2             852.1           893.7    3     41.30
81     318.8               212.5      0.0  155.7              14.3             852.1           880.4    3     25.20
82     401.8                94.7      0.0  147.4              11.4             946.8           852.1    3     41.10
83     362.6               189.0      0.0  164.9              11.6             944.7           755.8    3     35.30
84     323.7               282.8      0.0  183.8              10.3             942.7           659.9    3     28.30
85     379.5               151.2      0.0  153.9              15.9            1134.3           605.0    3     28.60
87     286.3               200.9      0.0  144.7              11.2            1004.6           803.7    3     24.40
89     439.0               177.0      0.0  186.0              11.1             884.9           707.9    3     39.30
90     389.9               189.0      0.0  145.9              22.0             944.7           755.8    3     40.60
92     337.9               189.0      0.0  174.9               9.5             944.7           755.8    3     24.10
93     374.0               189.2      0.0  170.1              10.1             926.1           756.7    7     46.20
94     313.3               262.2      0.0  175.5               8.6            1046.9           611.8    7     42.80
95     425.0               106.3      0.0  153.5              16.5             852.1           887.1    7     49.20
96     425.0               106.3      0.0  151.4              18.6             936.0           803.7    7     46.80
97     375.0                93.8      0.0  126.6              23.4             852.1           992.6    7     45.70
98     475.0               118.8      0.0  181.1               8.9             852.1           781.5    7     55.60
99     469.0               117.2      0.0  137.8              32.2             852.1           840.5    7     54.90
101    388.6                97.1      0.0  157.9              12.1             852.1           925.7    7     34.90
102    531.3                 0.0      0.0  141.8              28.2             852.1           893.7    7     46.90
104    318.8               212.5      0.0  155.7              14.3             852.1           880.4    7     33.40
105    401.8                94.7      0.0  147.4              11.4             946.8           852.1    7     54.10
106    362.6               189.0      0.0  164.9              11.6             944.7           755.8    7     55.90
107    323.7               282.8      0.0  183.8              10.3             942.7           659.9    7     49.80
108    379.5               151.2      0.0  153.9              15.9            1134.3           605.0    7     47.10
110    286.3               200.9      0.0  144.7              11.2            1004.6           803.7    7     38.00
112    439.0               177.0      0.0  186.0              11.1             884.9           707.9    7     56.10
113    389.9               189.0      0.0  145.9              22.0             944.7           755.8    7     59.09
114    362.6               189.0      0.0  164.9              11.6             944.7           755.8    7     22.90
115    337.9               189.0      0.0  174.9               9.5             944.7           755.8    7     35.10
116    374.0               189.2      0.0  170.1              10.1             926.1           756.7   28     61.09
117    313.3               262.2      0.0  175.5               8.6            1046.9           611.8   28     59.80
118    425.0               106.3      0.0  153.5              16.5             852.1           887.1   28     60.29
119    425.0               106.3      0.0  151.4              18.6             936.0           803.7   28     61.80
120    375.0                93.8      0.0  126.6              23.4             852.1           992.6   28     56.70
121    475.0               118.8      0.0  181.1               8.9             852.1           781.5   28     68.30
122    469.0               117.2      0.0  137.8              32.2             852.1           840.5   28     66.90
124    388.6                97.1      0.0  157.9              12.1             852.1           925.7   28     50.70
125    531.3                 0.0      0.0  141.8              28.2             852.1           893.7   28     56.40
127    318.8               212.5      0.0  155.7              14.3             852.1           880.4   28     55.50
128    401.8                94.7      0.0  147.4              11.4             946.8           852.1   28     68.50
129    362.6               189.0      0.0  164.9              11.6             944.7           755.8   28     71.30
130    323.7               282.8      0.0  183.8              10.3             942.7           659.9   28     74.70
131    379.5               151.2      0.0  153.9              15.9            1134.3           605.0   28     52.20
133    286.3               200.9      0.0  144.7              11.2            1004.6           803.7   28     67.70
135    439.0               177.0      0.0  186.0              11.1             884.9           707.9   28     66.00
136    389.9               189.0      0.0  145.9              22.0             944.7           755.8   28     74.50
138    337.9               189.0      0.0  174.9               9.5             944.7           755.8   28     49.90
139    374.0               189.2      0.0  170.1              10.1             926.1           756.7   56     63.40
140    313.3               262.2      0.0  175.5               8.6            1046.9           611.8   56     64.90
141    425.0               106.3      0.0  153.5              16.5             852.1           887.1   56     64.30
142    425.0               106.3      0.0  151.4              18.6             936.0           803.7   56     64.90
143    375.0                93.8      0.0  126.6              23.4             852.1           992.6   56     60.20
144    475.0               118.8      0.0  181.1               8.9             852.1           781.5   56     72.30
145    469.0               117.2      0.0  137.8              32.2             852.1           840.5   56     69.30
147    388.6                97.1      0.0  157.9              12.1             852.1           925.7   56     55.20
148    531.3                 0.0      0.0  141.8              28.2             852.1           893.7   56     58.80
150    318.8               212.5      0.0  155.7              14.3             852.1           880.4   56     66.10
151    401.8                94.7      0.0  147.4              11.4             946.8           852.1   56     73.70
152    362.6               189.0      0.0  164.9              11.6             944.7           755.8   56     77.30
154    323.7               282.8      0.0  183.8              10.3             942.7           659.9   56     80.20
155    379.5               151.2      0.0  153.9              15.9            1134.3           605.0   56     54.90
157    286.3               200.9      0.0  144.7              11.2            1004.6           803.7   56     72.99
159    439.0               177.0      0.0  186.0              11.1             884.9           707.9   56     71.70
160    389.9               189.0      0.0  145.9              22.0             944.7           755.8   56     79.40
162    337.9               189.0      0.0  174.9               9.5             944.7           755.8   56     59.89
163    374.0               189.2      0.0  170.1              10.1             926.1           756.7   91     64.90
164    313.3               262.2      0.0  175.5               8.6            1046.9           611.8   91     66.60
165    425.0               106.3      0.0  153.5              16.5             852.1           887.1   91     65.20
166    425.0               106.3      0.0  151.4              18.6             936.0           803.7   91     66.70
167    375.0                93.8      0.0  126.6              23.4             852.1           992.6   91     62.50
169    475.0               118.8      0.0  181.1               8.9             852.1           781.5   91     74.19
170    469.0               117.2      0.0  137.8              32.2             852.1           840.5   91     70.70
172    388.6                97.1      0.0  157.9              12.1             852.1           925.7   91     57.60
173    531.3                 0.0      0.0  141.8              28.2             852.1           893.7   91     59.20
175    318.8               212.5      0.0  155.7              14.3             852.1           880.4   91     68.10
176    401.8                94.7      0.0  147.4              11.4             946.8           852.1   91     75.50
177    362.6               189.0      0.0  164.9              11.6             944.7           755.8   91     79.30
178    379.5               151.2      0.0  153.9              15.9            1134.3           605.0   91     56.50
180    286.3               200.9      0.0  144.7              11.2            1004.6           803.7   91     76.80
182    439.0               177.0      0.0  186.0              11.1             884.9           707.9   91     73.30
183    389.9               189.0      0.0  145.9              22.0             944.7           755.8   91     82.60
185    337.9               189.0      0.0  174.9               9.5             944.7           755.8   91     67.80
186    222.4                 0.0     96.7  189.3               4.5             967.1           870.3    3     11.58
187    222.4                 0.0     96.7  189.3               4.5             967.1           870.3   14     24.45
188    222.4                 0.0     96.7  189.3               4.5             967.1           870.3   28     24.89
189    222.4                 0.0     96.7  189.3               4.5             967.1           870.3   56     29.45
190    222.4                 0.0     96.7  189.3               4.5             967.1           870.3  100     40.71
191    233.8                 0.0     94.6  197.9               4.6             947.0           852.2    3     10.38
192    233.8                 0.0     94.6  197.9               4.6             947.0           852.2   14     22.14
193    233.8                 0.0     94.6  197.9               4.6             947.0           852.2   28     22.84
194    233.8                 0.0     94.6  197.9               4.6             947.0           852.2   56     27.66
195    233.8                 0.0     94.6  197.9               4.6             947.0           852.2  100     34.56
196    194.7                 0.0    100.5  165.6               7.5            1006.4           905.9    3     12.45

### 3. View the number of rows and columns in the data frame

In [27]:
df.shape

(1032, 9)

### 4. Get the dataframe information about the data set.

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1032 non-null   float64
 1   Blast Furnace Slag  1032 non-null   float64
 2   Fly Ash             1032 non-null   float64
 3   Water               1031 non-null   float64
 4   Superplasticizer    1032 non-null   float64
 5   Coarse Aggregate    1032 non-null   float64
 6   Fine Aggregate      1032 non-null   float64
 7   Age                 1032 non-null   int64
 8   Strength            1032 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.7 KB

### 5. Check the empty value.

In [35]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 1
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The empty value is in column `Water`. Show row:

In [36]:
df[df['Water'].isnull()]

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
4,198.6,132.4,0.0,NaN,0.0,978.4,825.5,360,44.3

### 6. Replace Empty Values Using the value that appears most frequently.

In [38]:
df['Water'] = df['Water'].fillna(df['Water'].mode()[0])

### 7. Check and Discovering Duplicates.

In [41]:
df[df.duplicated()]

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
77,425.0,106.3,0.0,153.5,16.5,852.1,887.1,3,33.40
80,425.0,106.3,0.0,153.5,16.5,852.1,887.1,3,33.40
86,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
88,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
91,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
100,425.0,106.3,0.0,153.5,16.5,852.1,887.1,7,49.20
103,425.0,106.3,0.0,153.5,16.5,852.1,887.1,7,49.20
109,362.6,189.0,0.0,164.9,11.6,944.7,755.8,7,55.90
111,362.6,189.0,0.0,164.9,11.6,944.7,755.8,7,55.90
123,425.0,106.3,0.0,153.5,16.5,852.1,887.1,28,60.29
126,425.0,106.3,0.0,153.5,16.5,852.1,887.1,28,60.29
132,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
134,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
137,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
146,425.0,106.3,0.0,153.5,16.5,852.1,887.1,56,64.30
149,425.0,106.3,0.0,153.5,16.5,852.1,887.1,56,64.30
153,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
156,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
158,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
161,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
168,375.0,93.8,0.0,126.6,23.4,852.1,992.6,91,62.50
171,425.0,106.3,0.0,153.5,16.5,852.1,887.1,91,65.20
174,425.0,106.3,0.0,153.5,16.5,852.1,887.1,91,65.20
179,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
181,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
184,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
811,252.0,0.0,0.0,185.0,0.0,1111.0,784.0,28,19.69

### 8. Removing Duplicates.

In [42]:
df.drop_duplicates(inplace=True)

### 9. Export data

In [47]:
df.to_csv('clean_data.csv')